version: '3'
services:
    server:
        build:
            context: ./
        ports: 
            - "5000:5000"
        restart: always
        env_file: 
            ".env"
        stdin_open: true
        tty: true
    db:
        build:
            context: ./db/
        env_file: 
            "./db/.env"
        ports: 
            - "5432:5432"
        restart: always

        