version: '3'
services:  
  swg-frontend:
    build: ./frontend
    restart: on-failure
    environment:
      - NGINX_PORT=80
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swg-frontend.rule=PathPrefix(`/^((?!api).)*$$/`)"
   
  reverse-proxy:
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # traefik config file
      - "$PWD/gateway/traefik.dev.toml:/etc/traefik/traefik.toml"

  swg-backend:
      build: ./backend
      expose:
        - "5000"
      volumes:
        - ./backend:/app
      restart: always
      environment:
        FLASK_ENV: development
        FLASK_DEBUG: 1
      stdin_open: true
      tty: true
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swg-backend.rule=PathPrefix(`/api/v1/`)"
