version: '3'
services:
    server:
        build:
            context: ./
        ports: 
            - "8000:8000"
        restart: always
        volumes: 
            - "/Users/jonjohnson/dev/swg/swg-website:/app"
        env_file: 
            ".env"
        stdin_open: true
        tty: true
        